spring:
  application:
    name: spring-boot-azure

  # JPA Configuration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none # Prevents Hibernate from automatically creating/dropping tables

  # PostgreSQL Datasource Configuration
  datasource:
    url: jdbc:postgresql://ermix.postgres.database.azure.com:5432/sb-azure-db
    username: userazure
    password: userazure
    driver-class-name: org.postgresql.Driver

  # Flyway Migration Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # Allows Flyway to start with existing databases
    validate-on-migrate: true # Validates migrations on each run
#    schemas: spring-boot-azure # Specifies schema to be used

  # Docker Support Configuration
  docker:
    compose:
      stop:
        command: down # Stops Docker Compose using 'docker-compose down'

# Logging Configuration (Optional)
logging:
  level:
    org.flywaydb: INFO   # Logs Flyway migration process
    org.hibernate.SQL: DEBUG  # Logs SQL queries for debugging purposes
