CREATE TABLE account_operation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    operation_date  TIMESTAMP WITHOUT TIME ZONE,
    amount          DOUBLE PRECISION                        NOT NULL,
    type            VARCHAR(255),
    bank_account_id VARCHAR(255),
    description     VARCHAR(255),
    CONSTRAINT pk_accountoperation PRIMARY KEY (id)
);

CREATE TABLE bank_account
(
    id            VARCHAR(255)     NOT NULL,
    type          VARCHAR(4),
    balance       DOUBLE PRECISION NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    status        VARCHAR(255),
    customer_id   BIGINT,
    over_draft    DOUBLE PRECISION NOT NULL,
    interest_rate DOUBLE PRECISION ,
    CONSTRAINT pk_bankaccount PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

ALTER TABLE account_operation
    ADD CONSTRAINT FK_ACCOUNTOPERATION_ON_BANKACCOUNT FOREIGN KEY (bank_account_id) REFERENCES bank_account (id);

ALTER TABLE bank_account
    ADD CONSTRAINT FK_BANKACCOUNT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);